"""Validation and normalization for speaking tips structured output."""

import logging

from app.schemas.speaking_tips_schema import SpeakingTipLinkingNote, SpeakingTipsPayload
from app.services.format.speaking_tips_response_format import (
    SPEAKING_TIPS_LINKING_NOTES_MAX,
    SPEAKING_TIPS_STRESS_WORDS_MAX,
)
from app.utils.json_payload import StructuredOutputError, extract_json_payload

logger = logging.getLogger(__name__)


def _normalize_string(value: object, field_name: str, *, allow_empty: bool = False) -> str:
    """Normalize one string field from speaking tips output."""
    if not isinstance(value, str):
        raise StructuredOutputError(f"Speaking tips field '{field_name}' must be a string.")

    normalized = value.strip()
    if not allow_empty and not normalized:
        raise StructuredOutputError(f"Speaking tips field '{field_name}' cannot be empty.")
    return normalized


def parse_speaking_tips(raw_text: str) -> SpeakingTipsPayload:
    """Validate and normalize speaking tips generated by the LLM.

    Raises:
        StructuredOutputError: If the payload shape or content is invalid.
    """
    payload = extract_json_payload(raw_text)
    if not isinstance(payload, dict):
        logger.warning("Speaking tips structured output was not a JSON object.")
        raise StructuredOutputError("Speaking tips output must be a JSON object.")

    raw_stress_words = payload.get("stress_words")
    if not isinstance(raw_stress_words, list):
        logger.warning("Speaking tips output missing array field 'stress_words'.")
        raise StructuredOutputError("Speaking tips field 'stress_words' must be an array.")

    stress_words: list[str] = []
    for item in raw_stress_words:
        if not isinstance(item, str):
            raise StructuredOutputError("Each speaking tips stress word must be a string.")
        word = item.strip()
        if word:
            stress_words.append(word)
    stress_words = stress_words[:SPEAKING_TIPS_STRESS_WORDS_MAX]

    raw_linking_notes = payload.get("linking_notes")
    if not isinstance(raw_linking_notes, list):
        logger.warning("Speaking tips output missing array field 'linking_notes'.")
        raise StructuredOutputError("Speaking tips field 'linking_notes' must be an array.")

    linking_notes: list[SpeakingTipLinkingNote] = []
    for item in raw_linking_notes[:SPEAKING_TIPS_LINKING_NOTES_MAX]:
        if not isinstance(item, dict):
            raise StructuredOutputError("Each linking note must be an object.")
        phrase = _normalize_string(item.get("phrase"), "phrase")
        tip = _normalize_string(item.get("tip"), "tip")
        linking_notes.append(SpeakingTipLinkingNote(phrase=phrase, tip=tip))

    return SpeakingTipsPayload(
        stress_words=stress_words,
        linking_notes=linking_notes,
        more_spoken_text=_normalize_string(payload.get("more_spoken_text"), "more_spoken_text"),
        note_text=_normalize_string(payload.get("note_text"), "note_text", allow_empty=True),
    )
